package com.airbnb.deeplinkdispatch.gradleplugin

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Task that relocates the KSP-generated assets from the resources directory to a safe location.
 *
 * This task must run after KSP and before any asset merge tasks. It moves the asset
 * files out of the KSP resources directory to prevent them from being included as
 * Java resources when this library is used as a project dependency.
 *
 * The assets are the binary match index files generated by the DeepLinkDispatch processor
 * for KSP-based builds. They will be merged into the final assets via the asset transform task.
 *
 * This is a separate task (rather than a doLast on KSP) because doLast doesn't run when
 * KSP is restored FROM-CACHE. This task will always run after KSP, even if KSP was cached.
 */
abstract class RelocateDeepLinkAssetsTask : DefaultTask() {

    /**
     * The directory where KSP generates the asset files.
     * Path: build/generated/ksp/<variant>/resources/assets/deeplinkdispatch/
     */
    // Using @InputFiles (instead of @InputDirectory) so the task can still execute when the
    // directory hasn't been created yet — modules with no deep links never produce this dir.
    @get:InputFiles
    @get:Optional
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val kspAssetsDir: DirectoryProperty

    /**
     * The safe location where assets will be moved to.
     * Path: build/intermediates/deeplinkdispatch/<variant>/assets/deeplinkdispatch/
     */
    @get:OutputDirectory
    abstract val safeAssetsDir: DirectoryProperty

    init {
        // Force the task to run when the source directory exists with files.
        // Gradle's default up-to-date check compares content, but this task also *removes*
        // the source files (to keep them out of Java-resource processing), so if KSP is
        // restored FROM-CACHE we need to run again to re-delete them.
        outputs.upToDateWhen {
            val sourceDir = kspAssetsDir.orNull?.asFile
            sourceDir == null || !sourceDir.exists() || sourceDir.listFiles()?.isEmpty() != false
        }
    }

    @TaskAction
    fun taskAction() {
        val sourceDir = kspAssetsDir.orNull?.asFile
        val destDir = safeAssetsDir.get().asFile

        if (sourceDir != null && sourceDir.exists() && sourceDir.isDirectory) {
            val files = sourceDir.listFiles()?.filter { it.isFile }.orEmpty()
            if (files.isNotEmpty()) {
                destDir.mkdirs()
                files.forEach { file ->
                    file.copyTo(destDir.resolve(file.name), overwrite = true)
                    file.delete()
                }
                // Clean up empty parent dirs up to (but not including) the `resources` root
                // so the dir tree doesn't leak into Java-resource processing.
                var parentDir: java.io.File? = sourceDir
                while (parentDir != null &&
                    parentDir.name != "resources" &&
                    parentDir.isDirectory &&
                    parentDir.list()?.isEmpty() == true
                ) {
                    val nextParent = parentDir.parentFile
                    parentDir.delete()
                    parentDir = nextParent
                }
            }
        }
        // If neither source nor dest has files, no assets were generated — fine for modules
        // without deep links. If source is gone but dest has the previously-moved files, they
        // remain valid across incremental builds.
    }
}
